### PR TITLE
251 testing groups

### PR DESCRIPTION
**Pull request by KentonMewling**

### CODE REVIEW

**Review by GMcLachlan45 — CHANGES_REQUESTED** [review]
We can talk this over a bit more later, but if we're using PestPHP then we should use all of its syntax. 

It's a pretty easy switch over so you should be able to fix it all

**Review by GMcLachlan45 — APPROVED** [review]

**Comment by OneInA1E6** [comment]
conflicts are rough

**Comment by mvallido** [comment]
Don't edit code in GitHub please

**Comment by KentonMewling** [comment]
> Don't edit code in GitHub please

dont tell me what to do

**Pull request merged**
